### ISSUE TITLE
Failure in downloading solc 0.5.17

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#10373]
seems to happen randomly so maybe nothing much

```
Error HH501: Couldn't download compiler version 0.5.17+commit.d19bba13. Please check your internet connection and try again.
#29 156.9 ➤ YN0000:
#29 156.9 ➤ YN0000: HardhatError: HH501: Couldn't download compiler version 0.5.17+commit.d19bba13. Please check your internet connection and try again.
#29 156.9 ➤ YN0000:     at /home/unlock/packages/contracts/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:175:15
#29 156.9 ➤ YN0000:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#29 156.9 ➤ YN0000:     at CompilerDownloader.downloadCompiler (/home/unlock/packages/contracts/node_modules/hardhat/src/internal/solidity/compiler/downloader.ts:150:5)
#29 156.9 ➤ YN0000:     at SimpleTaskDefinition.action (/home/unlock/packages/contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:551:9)
#29 156.9 ➤ YN0000:     at Environment._runTaskDefinition (/home/unlock/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
#29 156.9 ➤ YN0000:     at Environment.run (/home/unlock/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
#29 156.9 ➤ YN0000:     at SimpleTaskDefinition.action (/home/unlock/packages/contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:678:36)
#29 156.9 ➤ YN0000:     at Environment._runTaskDefinition (/home/unlock/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
#29 156.9 ➤ YN0000:     at Environment.run (/home/unlock/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
#29 156.9 ➤ YN0000:     at Environment._runTaskDefinition (/home/unlock/packages/contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
#29 156.9 ➤ YN0000:
#29 156.9 ➤ YN0000:     Caused by: BodyTimeoutError: Body Timeout Error
#29 156.9 ➤ YN0000:         at Timeout.onParserTimeout [as _onTimeout] (/home/unlock/node_modules/undici/lib/client.js:898:28)
#29 156.9 ➤ YN0000:         at listOnTimeout (node:internal/timers:561:11)
#29 156.9 ➤ YN0000:         at processTimers (node:internal/timers:502:7)
```

**Comment by julien51** [comment]
I have not see this in a while... closing!
