### ISSUE TITLE
Issue with oracle when deploying locally

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11371]
When deploying locally with `yarn run hardhat deploy --unlock-version 11 --public-lock-version 12` we have an error:

```
UNLOCK SETUP > Unlock proxy deployed to: 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0 (tx: 0x3e515ee4f633974a85ba9eada4fdd7b463babdff939f259427e44188f048a991)  - implementation at: 0x5FbDB2315678afecb367f032d93F642f64180aa3
PUBLIC LOCK > Deploying lock template on localhost for released version 12 with signer 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
PUBLIC LOCK > deployed v12 to : 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9 (tx: 0x8885cdd609dc1f85174ea532777df057369d065f0b208c191ee6994b0231ddff)
LOCK TEMPLATE SETUP > Setting up PublicLock version 12
UNLOCK SETUP> Template set for Lock (tx: 0xdbc2b7c1c98ef5808c3b79360359b813a62f48fd4ec9c1f5eb0ec082de5cda26)
UDT SETUP > UDT v3 (w proxy) deployed to: 0xa513E6E4b8f2a923D98304ec87F64353C4D5C853 (tx: 0x8217f3bdb3a2a219c29c82eb950c118d248d4584d08008b2d05a61f41b37bafa)
UNLOCK DEPLOYMENT > Pre-minted 1000000.0 UDT to deployer
UNLOCK DEPLOYMENT > grant minting permissions to the Unlock Contract
UNLOCK DEPLOYMENT > minter renounced minter role
WETH > deployed to : 0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6 (tx: 0x5d100299ee2622ec33e7577805ba13564ec784e48745272c10cb6957ce6333d7
UNLOCK DEPLOYMENT > WETH deployed to : 0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6
UNISWAP/WETH SETUP > Using WETH contract at: 0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6
UNISWAP/WETH SETUP > Deploying Uniswap contracts using 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
UNISWAP/WETH SETUP > Uniswap V2 Factory deployed to : 0x8A791620dd6260079BF849Dc5567aDC3F2FdC318 (tx: 0xcb4a8b3bfd50b885afbfe1378e751e7eed85710dd6bd70b12b41bc4a4ff8d34a)
UNISWAP/WETH SETUP > Router V02 deployed to :  0x610178dA211FEF7D417bC0e6FeD39F05609AD788 (tx: 0xf4e5cc7eb0a0a94f1e335e5f58985b88c01b99b49043076e85f42e5a10b630c4)
UNLOCK DEPLOYMENT > UDT approved Uniswap Router for 1000.0 ETH
UNLOCK DEPLOYMENT > added liquidity to uniswap 1000.0
UNISWAP ORACLE > Oracle deployed at: 0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82  (tx: 0xa0b5a2307835afa41e471293b3f8bb24f751e8ef06bd366d6fcc799b78b3b76b)
UNLOCK CONFIG > Configuring Unlock with the following:
      - udtAddress: 0xa513E6E4b8f2a923D98304ec87F64353C4D5C853
      - wethAddress: 0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6
      - estimatedGasForPurchase: 200000
      - symbol: KEY
      - locksmithURI: https://locksmith.unlock-protocol.com/api/key/31337/
      - chainId: 31337
  
UNLOCK CONFIG > Unlock configured properly. (tx: 0xe7d718d3167d193b715131085c3c667644814522df850ff445c490e27b962244)

An unexpected error occurred:

Error: Transaction reverted without a reason string
    at <UnrecognizedContract>.<unknown> (0x8a791620dd6260079bf849dc5567adc3f2fdc318)
    at UniswapOracleV3.update (contracts/utils/UniswapOracleV3.sol:49)
    at Unlock.setOracle (contracts/past-versions/UnlockV11.sol:2553)
    at <UnrecognizedContract>.<unknown> (0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatNode._mineBlockWithPendingTxs (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1815:23)
    at HardhatNode.mineBlock (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:504:16)
    at EthModule._sendTransactionAndReturnHash (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)
    at HardhatNetworkProvider.request (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at EthersProviderWrapper.send (/Users/julien/repos/unlock/packages/hardhat-plugin/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

This error happens when running `set:unlock-oracle`.

**Comment by clemsos** [comment]
I have removed the deployment steps of Uniswap V2 from our local deploy suite. The Unlock Oracle now only supports Uniswap V3 and v3 is better tested against a forked network.
