### ISSUE TITLE
Add test for "live" proposal that logs events

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13504]
Our test suite for proposals assume that the proposal code will be submitted as code first but that won't always be the case.
Ideally we should always ask for the code, but that will not always be the case.
We should write tests that will at least "show" what the proposal do, based on the events being triggered, and, if possible will even "decode" the function(s) call(s) to see what other contracts might be called.

**Comment by clemsos** [comment]
This was added in #13504. Note that we log the log but often they come without the relevant ABI. Also we dont trace transactions o we won't have native tokens transfer showing up there.

A better approach will be to have a script that runs the full cycle on tenderly so we have full trace + events. All parts are there so that wont be so difficult to assemble it seems

**Comment by julien51** [comment]
Unfortunately, something is not working quite as expected here:

```
ress 0x440d9D4E66d39bb28FB58729Cb4D3ead2A595591 --tx-id 0xcffa5df0cc243334582cc1fb070d9454d537a92d2d6b09da3d506d2098b0a43a

⚠️ Using account from DEPLOYER_PRIVATE_KEY environment variable.
Running a fork of Ethereum (1)...
GOV (dev) > gov contract: 0x440d9D4E66d39bb28FB58729Cb4D3ead2A595591
GOV (dev) > Delegating UDT to bypass quorum (udt: 0x90DE74265a416e1393A450752175AED98fe11517)
An unexpected error occurred:

TypeError: Cannot destructure property 'args' of 'event' as it is undefined.
    at getEvent (/Users/julien/repos/unlock/packages/hardhat-helpers/dist/index.js:46160:11)
    at main (/Users/julien/repos/unlock/governance/scripts/gov/index.js:40:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SimpleTaskDefinition.action (/Users/julien/repos/unlock/governance/tasks/gov.js:28:14)
    at Environment._runTaskDefinition (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/core/runtime-environment.ts:358:14)
    at Environment.run (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/core/runtime-environment.ts:191:14)
    at main (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/cli/cli.ts:323:7)```

**Comment by clemsos** [comment]
weird that works on my side 

```
RUN_FORK=1 yarn hardhat gov --proposal-id 78493169475352541242368603715437523819117665991450552338312919834960142602740 --gov-address 0x440d9D4E66d39bb28FB58729Cb4D3ead2A595591 --tx-id 0xcffa5df0cc243334582cc1fb070d9454d537a92d2d6b09da3d506d2098b0a43a
⚠️ Missing DEPLOYER_PRIVATE_KEY environment variable. Please set one. In the meantime, we will use default settings
Running a fork of Ethereum (1)...
GOV (dev) > gov contract: 0x440d9D4E66d39bb28FB58729Cb4D3ead2A595591
GOV (dev) > Delegating UDT to bypass quorum (udt: 0x90DE74265a416e1393A450752175AED98fe11517)
GOV VOTE (dev) > 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 delegated quorum to 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 (total votes: 15000.0,quorum: 7500.0)
GOV VOTE > proposal ID : 78493169475352541242368603715437523819117665991450552338312919834960142602740
GOV VOTE (dev) > Impersonate voter: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
GOV VOTE > voter 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266: power 15000.0  (quorum 7500.0)
GOV VOTE > vote casted: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 approves (weigth: 0) (txid: 0x5d263da3631e83501d2ac045a471c89fceff880aa87e10f54cc33133fda1f615)
GOV VOTE > proposal ID : 78493169475352541242368603715437523819117665991450552338312919834960142602740
GOV VOTE > proposal ID : 78493169475352541242368603715437523819117665991450552338312919834960142602740
GOV VOTE > proposal ID : 78493169475352541242368603715437523819117665991450552338312919834960142602740
GOV VOTE > proposal ID : 78493169475352541242368603715437523819117665991450552338312919834960142602740
GOV VOTE > proposal ID : 78493169475352541242368603715437523819117665991450552338312919834960142602740
GOV VOTE (dev) > Impersonate voter: 0xa39b44c4AFfbb56b76a1BF1d19Eb93a5DfC2EBA9
GOV VOTE (dev) > Impersonate voter: 0xF5C28ce24Acf47849988f147d5C75787c0103534
GOV VOTE (dev) > Impersonate voter: 0xc0948A2f0B48A2AA8474f3DF54FD7C364225AD7d
GOV VOTE (dev) > Impersonate voter: 0xD2BC5cb641aE6f7A880c3dD5Aee0450b5210BE23
GOV VOTE (dev) > Impersonate voter: 0xCA7632327567796e51920F6b16373e92c7823854
GOV VOTE > voter already voted
GOV VOTE > voter 0xa39b44c4AFfbb56b76a1BF1d19Eb93a5DfC2EBA9: power 0.0  (quorum 7500.0)
GOV VOTE > voter 0xF5C28ce24Acf47849988f147d5C75787c0103534: power 0.0  (quorum 7500.0)
GOV VOTE > voter 0xc0948A2f0B48A2AA8474f3DF54FD7C364225AD7d: power 5052.139986505625750471  (quorum 7500.0)
GOV VOTE > voter 0xCA7632327567796e51920F6b16373e92c7823854: power 3014.420000000000000096  (quorum 7500.0)
GOV VOTE > vote casted: 0xa39b44c4AFfbb56b76a1BF1d19Eb93a5DfC2EBA9 approves (weigth: 0) (txid: 0x41d9a1135e6f8d3d894b55d2b7c4000fe312105effa416295534727d21cd2ea9)
GOV VOTE > vote casted: 0xF5C28ce24Acf47849988f147d5C75787c0103534 approves (weigth: 0) (txid: 0x764102b51e3514e8ea3d3dc9264977e0255fe5ef05c2616cac9eb11e51509142)
GOV VOTE > vote casted: 0xc0948A2f0B48A2AA8474f3DF54FD7C364225AD7d approves (weigth: 5052139986505625750471) (txid: 0x400f4ceae211ec9f472766e71c98dc6243670f8009805b24379204b3082434b5)
GOV VOTE > vote casted: 0xCA7632327567796e51920F6b16373e92c7823854 approves (weigth: 3014420000000000000096) (txid: 0x2c352a594881cc0d95d64b397d45cf8a023a06c68aa0a225bc5800e8ab2bbb3a)
GOV QUEUE > closing voting period (advancing to block 19551595)
GOV QUEUE > Current proposal Succeeded - votes (against, for, abstain): 3077878951335911045424,11092693451259301332524,0
GOV QUEUE > Proposal queued. ETA :Mon Apr 01 2024 20:10:41 GMT+0200 (Central European Summer Time) (tx: 0xf9b644bc1742f51cddd6115213bc5b2809c79e507e33dab609c3002af64e6045)
GOV EXEC > : increasing currentTime Fri Mar 29 2024 19:10:41 GMT+0100 (Central European Standard Time) to eta Mon Apr 01 2024 20:10:41 GMT+0200 (Central European Summer Time)
An unexpected error occurred:

Error: VM Exception while processing transaction: reverted with reason string 'TimelockController: underlying transaction reverted'
    at <UnrecognizedContract>.<unknown> (0x17eedfb0a6e6e06e95b3a1f928dc4024240bc76b)
    at <UnrecognizedContract>.<unknown> (0x440d9d4e66d39bb28fb58729cb4d3ead2a595591)
    at <UnrecognizedContract>.<unknown> (0x440d9d4e66d39bb28fb58729cb4d3ead2a595591)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by julien51** [comment]
I tried again, after a fully clean master and I still have the error:

```
➜  governance git:(master) RUN_FORK=1 yarn hardhat gov --proposal-id 78493169475352541242368603715437523819117665991450552338312919834960142602740 --gov-address 0x440d9D4E66d39bb28FB58729Cb4D3ead2A595591 --tx-id 0xcffa5df0cc243334582cc1fb070d9454d537a92d2d6b09da3d506d2098b0a43a

⚠️ Using account from DEPLOYER_PRIVATE_KEY environment variable.
Running a fork of Ethereum (1)...
GOV (dev) > gov contract: 0x440d9D4E66d39bb28FB58729Cb4D3ead2A595591
GOV (dev) > Delegating UDT to bypass quorum (udt: 0x90DE74265a416e1393A450752175AED98fe11517)
An unexpected error occurred:

TypeError: Cannot destructure property 'args' of 'event' as it is undefined.
    at getEvent (/Users/julien/repos/unlock/packages/hardhat-helpers/dist/index.js:46074:11)
    at main (/Users/julien/repos/unlock/governance/scripts/gov/index.js:40:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SimpleTaskDefinition.action (/Users/julien/repos/unlock/governance/tasks/gov.js:28:14)
    at Environment._runTaskDefinition (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/core/runtime-environment.ts:358:14)
    at Environment.run (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/core/runtime-environment.ts:191:14)
    at main (/Users/julien/repos/unlock/node_modules/hardhat/src/internal/cli/cli.ts:323:7)
```

**Comment by julien51** [comment]
It's passing now!
