### ISSUE TITLE
Hardhat plugin broken with ethers 6?

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13631]
I set up a new Hardhat project from scracth. I then added the Unlock hardhat plugin. Then in my scripts/tests I am trying to deploy the whole protocol with `await unlock.deployProtocol();` and I get the following error:

```

  1) TokenUriHook
       "before all" hook in "TokenUriHook":
     TypeError: Cannot read properties of undefined (reading 'wait')
      at deployUpgreadableContract (node_modules/@unlock-protocol/hardhat-plugin/src/utils.ts:56:29)
      at async deployUnlock (node_modules/@unlock-protocol/hardhat-plugin/src/deployProtocol.ts:38:28)
      at async deployProtocol (node_modules/@unlock-protocol/hardhat-plugin/src/deployProtocol.ts:105:18)
      at async Context.<anonymous> (test/TokenUriHook.ts:14:5)


```

I suspect this is an issue with the ethers version?

**Comment by StephanGerbeth** [comment]
@nomicfoundation/hardhat-toolbox@5.0.0 requires ethers@6.4.0. so it is not possible to use hardhat unlock plugin which requires ethers@5

**Comment by clemsos** [comment]
hey @StephanGerbeth the latest version of the plugin (0.2.1) now supports ethers6.
