### ISSUE TITLE
Flaky smart contract test

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#14005]
Will often fail on CI with the following error

```
  1) PublicLock upgrade  v9 > v10
       perform upgrade
         complete data migration
           preserves all keys data:

      AssertionError [ERR_ASSERTION]: '0x90F79bf6EB2c4f870365E785982E1f101E93b906' == '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
      + expected - actual

      -0x90F79bf6EB2c4f870365E785982E1f101E93b906
      +0x70997970C51812dc3A010C7d01b50e0d17dc79C8
      
      at Context.<anonymous> (test/Lock/upgrades/v10.js:204:18)

```

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/actions/runs/9422995925/job/25960463420

**Comment by clemsos** [comment]
```
  1) PublicLock upgrade  v9 > v10
       perform upgrade
         complete data migration
           preserves all keys data:

      AssertionError [ERR_ASSERTION]: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC' == '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
      + expected - actual

      -0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
      +0x70997970C51812dc3A010C7d01b50e0d17dc79C8
      
      at Context.<anonymous> (test/Lock/upgrades/v10.js:204:18)
```

**Comment by clemsos** [comment]
another one 

```
  1) PublicLock upgrade  v9 > v10
       perform upgrade
         complete data migration
           preserves all keys data:

      AssertionError [ERR_ASSERTION]: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC' == '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
      + expected - actual

      -0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
      +0x70997970C51812dc3A010C7d01b50e0d17dc79C8
      
      at Context.<anonymous> (test/Lock/upgrades/v10.js:204:18)

```
