### ISSUE TITLE
checking the PAYWALL_URL and PAYWALL_SCRIPT_URL definitions on netlify for unlock-app

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2070]
The netlify deployed unlock app is getting the environment variables PAYWALL_URL and PAYWALL_SCRIPT_URL from somewhere external to the app.

This is because of these lines in `next.config.js`:

```js
const requiredConfigVariables = {
  unlockEnv: process.env.UNLOCK_ENV || 'dev',
  httpProvider: process.env.HTTP_PROVIDER || '127.0.0.1',
  paywallUrl: process.env.PAYWALL_URL,
  paywallScriptUrl: process.env.PAYWALL_SCRIPT_URL,
  readOnlyProvider: process.env.READ_ONLY_PROVIDER,
  locksmithHost: process.env.LOCKSMITH_URI || 'http://127.0.0.1:8080',
  unlockAddress:
    process.env.UNLOCK_ADDRESS || '0x885EF47c3439ADE0CB9b33a4D3c534C99964Db93', // default for CI
}

Object.keys(requiredConfigVariables).forEach(configVariableName => {
  if (!requiredConfigVariables[configVariableName]) {
    if (requiredConfigVariables.unlockEnv === 'test') return
    if (requiredConfigVariables.unlockEnv === 'dev') {
      return console.error(
        `The configuration variable ${configVariableName} is falsy.`
      )
    }
    throw new Error(
      `The configuration variable ${configVariableName} is falsy.`
    )
  }
})
```

If `PAYWALL_URL` or `PAYWALL_SCRIPT_URL` is not defined, the script throws. One can verify this locally by running:

```bash
UNLOCK_ENV=staging npm run dev
```

It crashes with:

```bash
(node:59580) UnhandledPromiseRejectionWarning: Error: The configuration variable paywallUrl is falsy.
    at Object.keys.forEach.configVariableName (/Users/gregorybeaver/Documents/GitHub/unlock/unlock-app/next.config.js:30:11)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/gregorybeaver/Documents/GitHub/unlock/unlock-app/next.config.js:22:38)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.loadConfig [as default] (/Users/gregorybeaver/Documents/GitHub/unlock/unlock-app/node_modules/next-server/dist/server/config.js:54:34)
    at new Server (/Users/gregorybeaver/Documents/GitHub/unlock/unlock-app/node_modules/next-server/dist/server/next-server.js:31:48)
    at new DevServer (/Users/gregorybeaver/Documents/GitHub/unlock/unlock-app/node_modules/next/dist/server/next-dev-server.js:14:9)
    at module.exports (/Users/gregorybeaver/Documents/GitHub/unlock/unlock-app/node_modules/next/dist/server/next.js:6:16)
    at Promise (/Users/gregorybeaver/Documents/GitHub/unlock/unlock-app/src/_server.js:9:17)
    at new Promise (<anonymous>)
(node:59580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart
```

**Comment by julien51** [comment]
I think this is fixed?
