### ISSUE TITLE
Paywall crashes not work on staging

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2100]
While viewing https://staging.unlock-protocol.com/demo/0xdD3a0c4b88FA29d1BfCE5F526b0cacF3b79eF622

![Screen Shot 2019-03-15 at 10.26.21 AM.png](https://images.zenhubusercontent.com/5c7807999546cc1a88f4f864/b27499c5-9e64-4ce8-bbb9-0842b2b6357f)

main-97bf5c7c6308c6064cd6.js:1 Failed to execute 'replaceState' on 'History': A history state object with URL 'https://0xdd3a0c4b88fa29d1bfce5f526b0cacf3b79ef622/?origin=https%3A%2F%2Fstaging.unlock-protocol.com' cannot be created in a document with origin 'https://staging-paywall.unlock-protocol.com' and URL 'https://staging-paywall.unlock-protocol.com//0xdD3a0c4b88FA29d1BfCE5F526b0cacF3b79eF622/?origin=https%3A%2F%2Fstaging.unlock-protocol.com'.
Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://0xdd3a0c4b88fa29d1bfce5f526b0cacf3b79ef622/?origin=https%3A%2F%2Fstaging.unlock-protocol.com' cannot be created in a document with origin 'https://staging-paywall.unlock-protocol.com' and URL 'https://staging-paywall.unlock-protocol.com//0xdD3a0c4b88FA29d1BfCE5F526b0cacF3b79eF622/?origin=https%3A%2F%2Fstaging.unlock-protocol.com'.
    at t.value (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:25:140604)
    at new t (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:25:137359)
    at o (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:47:115422)
    at Object.e.createRouter (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:47:38103)
    at Object.<anonymous> (https://staging-paywall.unlock-protocol.com/_next/static/runtime/main-97bf5c7c6308c6064cd6.js:1:14063)
    at _ (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:65:245732)
    at Generator._invoke (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:65:245520)
    at Generator.t.(anonymous function) [as next] (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:65:245911)
    at i (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:39:30272)
    at s (https://staging-paywall.unlock-protocol.com/_next/static/chunks/commons.8a40e531be11452ec7c7.js:39:30470)

**Comment by cellog** [comment]
this issue is fixed. Follow-up issue #2105 will fully fix the paywall
