### ISSUE TITLE
Run smart contract tests without automine

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#2466]
Our smart contract test suite currently assumes that the nodes are running with "auto-mining" on (each transaction is immediately mined when the node receives it). 
We should remove that assumption and ensure that the smart contract test suite actually runs on any network (not just ganache).

**Comment by hardlydifficult** [comment]
this is a fix for #1944

**Comment by hardlydifficult** [comment]
Made some progress, but currently getting this error after approx 100 tests execute.  I'm currently unsure what may be causing this...

```
TypeError: this.removeListener is not a function
    at Object.receipt (E:\unlock3\smart-contracts\node_modules\truffle\build\webpack:\packages\truffle-contract\lib\handlers.js:134:1)
    at Function.start (E:\unlock3\smart-contracts\node_modules\truffle\build\webpack:\packages\truffle-contract\lib\override.js:56:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: this.removeListener is not a function
    at Object.receipt (E:\unlock3\smart-contracts\node_modules\truffle\build\webpack:\packages\truffle-contract\lib\handlers.js:134:1)
    at Function.start (E:\unlock3\smart-contracts\node_modules\truffle\build\webpack:\packages\truffle-contract\lib\override.js:56:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
E:\unlock3\smart-contracts\node_modules\mocha\lib\runner.js:707
  err.uncaught = true;
```

**Comment by julien51** [comment]
Where are we on this?

**Comment by hardlydifficult** [comment]
..no update since the last comment.  may be a truffle bug.  should probably give it another go, there have been a few updates that may have addressed this

**Comment by hardlydifficult** [comment]
This still fails with `this.removeListener is not a function` after approx 100 transactions are processed.

**Comment by julien51** [comment]
This is done, now that we are using HardHat!
