### ISSUE TITLE
Upgrade zOS to v2.0.1

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#502]
**Is your feature request related to a problem? Please describe.**
zos-cli hss undergone a major update. Unlock is still using the older version. The new version introduces a number of benefits, and, as zos hasn't been used to deploy yet, it's likely to be easier to upgrade now, before we start using it regularly.

**Describe the solution you'd like**
- Add `"zosversion": "2",` to the `zos.json` file,
- Change the zos-lib  version in `package.json` to ^2.0.1 .

**Describe alternatives you've considered**

**Additional context**
As zos is likely to play a critical role in deploying and allowing for upgradeability, it makes sense to use the new version, even if only to streamline the process and make it more reliable. There have been some significant changes to how zos handles the on-chain architecture of a deployed app, and improved security validation around potential contract storage conflicts as well.

Release notes here:
https://github.com/zeppelinos/zos/releases/tag/v2.0.0

**Comment by nfurfaro** [comment]
Note: I've done some work on this already, but ended up with one broken test as a result. Haven't resolved it yet.

**Comment by nfurfaro** [comment]
It (seemingly randomly) alternates between
`Error: AdminUpgradeabilityProxy error: Please call setProvider() first before calling new().` 
and
`Error: VM Exception while processing transaction: revert`,
but it's the same test failing every the time. 
```
51 passing (16s)
  21 pending
  1 failing

  1) Contract: Unlock
       Proxy Unlock contract
         "before each" hook for "should persist state between upgrades":
     Error: AdminUpgradeabilityProxy error: Please call setProvider() first before calling new().
      at Function.new (node_modules/truffle-contract/contract.js:344:15)
      at Context.<anonymous> (test/Unlock/UnlockProxy.js:17:26)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```
and then
```
51 passing (18s)
  21 pending
  1 failing

  1) Contract: Unlock
       Proxy Unlock contract
         "before each" hook for "should persist state between upgrades":
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by julien51** [comment]
Do you think the bug is Unlock-specific in any way?

**Comment by nfurfaro** [comment]
https://github.com/unlock-protocol/unlock/issues/195#issuecomment-415986365
