### ISSUE TITLE
Errors when testing the web-app, even when all tests pass

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#512]
**Describe the bug**
I have the most recent master branch. All test for smart contracts and unlock-app pass. However, in the output for the tests in `unlock-app` I get multiple errors.

**To Reproduce**
1. Checkout the master branch.
2. Install all dependencies in smart-contracts and in unlock-app.
3. in `unlock-app` run `npm run test`
4. Look at the output.

**Expected behavior**
I was expecting all tests to pass and no errors in the output.

**Output**
```
overlord @ ~/DAPPS/unlock/unlock-app : master  => npm run test

> unlock-app@0.1.0 test /Users/overlord/DAPPS/unlock/unlock-app
> NODE_ENV=test jest --env=jsdom

 PASS  src/__tests__/config.test.js
 PASS  src/__tests__/components/Web3Provider.test.js
 PASS  src/__tests__/utils/withConfig/correctRenderWithConfig.test.js
 PASS  src/__tests__/utils/withConfig/wrongNetwork.test.js
 PASS  src/__tests__/services/web3Service.test.js
  ● Console

    console.log src/services/web3Service.js:386
      Error: Invalid JSON RPC response: ""
          at Object.InvalidResponse (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/web3-core-helpers/src/errors.js:42:16)
          at XMLHttpRequest.request.onreadystatechange (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/web3-providers-http/
src/index.js:87:32)
          at XMLHttpRequest.Object.<anonymous>.XMLHttpRequestEventTarget.dispatchEvent (/Users/overlord/DAPPS/unlock/unlock-app/n
ode_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
          at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest._setReadyState (/Users/overlord/DAPPS/unlock/unlock-app/node_module
s/xhr2-cookies/xml-http-request.ts:219:8)
          at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest._onHttpRequestError (/Users/overlord/DAPPS/unlock/unlock-app/node_m
odules/xhr2-cookies/xml-http-request.ts:379:8)
          at OverriddenClientRequest.<anonymous> (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/xhr2-cookies/xml-http-request.ts:266:37)
          at OverriddenClientRequest.emit (events.js:182:13)
          at /Users/overlord/DAPPS/unlock/unlock-app/node_modules/nock/lib/request_overrider.js:221:11
          at process.internalTickCallback (internal/process/next_tick.js:70:11)
    console.log src/services/web3Service.js:422
      Error: Returned error: VM Exception while processing transaction: revert
          at Object.ErrorResponse (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/web3-core-helpers/src/errors.js:29:16)
          at /Users/overlord/DAPPS/unlock/unlock-app/node_modules/web3-core-requestmanager/src/index.js:140:36
          at XMLHttpRequest.request.onreadystatechange (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/web3-providers-http/src/index.js:91:13)
          at XMLHttpRequest.Object.<anonymous>.XMLHttpRequestEventTarget.dispatchEvent (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
          at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest._setReadyState (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
          at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest._onHttpResponseEnd (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
          at IncomingMessage.<anonymous> (/Users/overlord/DAPPS/unlock/unlock-app/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
          at IncomingMessage.emit (events.js:182:13)
          at endReadableNT (_stream_readable.js:1094:12)
          at internalTickCallback (internal/process/next_tick.js:72:19)
          at _tickCallback (internal/process/next_tick.js:47:5)
          at processImmediate (timers.js:605:7)

 PASS  src/__tests__/utils/withConfig/missingProvidersWithConfig.test.js
 PASS  src/__tests__/utils/duration.test.js
 PASS  src/__tests__/components/page/OpenGraphTags.test.js
 PASS  src/__tests__/components/page/TwitterTags.test.js
 PASS  src/__tests__/components/helpers/Balance.test.js
 PASS  src/__tests__/components/lock/ShowUnlessUserHasKeyToAnyLock.test.js
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: Invalid prop `locks` of type `array` supplied to `ShowUnlessUserHasKeyToAnyLock`, expected `obje
ct`.
          in ShowUnlessUserHasKeyToAnyLock (at ShowUnlessUserHasKeyToAnyLock.test.js:19)

 PASS  src/__tests__/middlewares/currencyConversionMiddleware.test.js
 PASS  src/__tests__/selectors/currency.test.js
 PASS  src/__tests__/constants.js
 PASS  src/__tests__/reducers/transactionReducer.test.js
 PASS  src/__tests__/actions/key.test.js
 PASS  src/__tests__/middlewares/lockMiddleware.test.js
  ● Console

    console.error src/middlewares/lockMiddleware.js:39
      Failed to connect to web3 service:
    console.error src/middlewares/lockMiddleware.js:40
      TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
          at _iterableToArrayLimit (/Users/overlord/DAPPS/unlock/unlock-app/src/middlewares/lockMiddleware.js:30:131)
          at _slicedToArray (/Users/overlord/DAPPS/unlock/unlock-app/src/middlewares/lockMiddleware.js:26:66)
          at /Users/overlord/DAPPS/unlock/unlock-app/src/middlewares/lockMiddleware.js:47:23
          at process.internalTickCallback (internal/process/next_tick.js:77:7)

 PASS  src/__tests__/pages/pages.test.js
 PASS  src/__tests__/reducers/errorReducer.test.js
 PASS  src/__tests__/components/helpers/Duration.test.js
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: Invalid prop `seconds` of type `string` supplied to `Duration`, expected `number`.
          in Duration (at Duration.test.js:10)

 PASS  src/__tests__/actions/transaction.test.js
 PASS  src/__tests__/components/creator/CreatorAccount.test.js
 PASS  src/__tests__/reducers/currencyReducer.test.js
 PASS  src/__tests__/reducers/accountReducer.test.js
 PASS  src/__tests__/components/creator/CreatorLock.test.js
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:19
      Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a re
ad-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
          in textarea (created by Context.Consumer)
          in StyledComponent (created by styled.textarea)
          in div (created by Context.Consumer)
          in StyledComponent (created by styled.div)
          in EmbedCodeSnippet (at CreatorLock.js:85)
          in div (created by Context.Consumer)
          in StyledComponent (created by styled.div)
          in div (created by Context.Consumer)
          in StyledComponent (created by styled.div)
          in CreatorLock (at CreatorLock.test.js:41)
          in Provider (at CreatorLock.test.js:40)

 PASS  src/__tests__/reducers/locksReducer.test.js
 PASS  src/__tests__/actions/provider.test.js
 PASS  src/__tests__/reducers/networkReducer.test.js
 PASS  src/__tests__/actions/error.test.js
 PASS  src/__tests__/actions/lock.test.js
 PASS  src/__tests__/actions/network.test.js
 PASS  src/__tests__/reducers/providerReducer.test.js
 PASS  src/__tests__/actions/currencyconvert.test.js
 PASS  src/__tests__/components/lock/Lock.test.js
 PASS  src/__tests__/reducers/keysReducer.test.js
 PASS  src/__tests__/actions/accounts.test.js

Test Suites: 36 passed, 36 total
Tests:       5 skipped, 142 passed, 147 total
Snapshots:   3 passed, 3 total
Time:        6.601s
Ran all test suites.
overlord @ ~/DAPPS/unlock/unlock-app : master  =>
```

**Desktop**
![image](https://user-images.githubusercontent.com/17053076/48280779-e1487800-e411-11e8-905a-cf3848315e79.png)
Editor: VS Code 1.28.2

**Comment by julien51** [comment]
Hooo these are not errors ;) Just console messages !
