### ISSUE TITLE
Use ZOS to deploy PublicLock template

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#5627]
In the `project.json` file, we currently have added only 2 contracts:
```
"contracts": {
    "Unlock": "Unlock",
    "UnlockDiscountToken": "UnlockDiscountToken"
  },
```
I believe adding a third contract, `PublicLock` to the project here will both simplify deployment (zos push will now deploy our PublicLock template as well) as well as make tracking the deployed address easier( as the PublicLock template's deployed address will be recorded in the network file, eg: `zos.mainnet.json`).

**Comment by nfurfaro** [comment]
Strange. After adding `PublicLock.sol` to the zos project I can't run tests.
```
overlord @ ~/DAPPS/unlock/smart-contracts : n44o-issue-5627  => yarn run test
yarn run v1.21.1
$ cross-env NODE_ENV=test truffle test --network development
Using network 'development'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Error: One or more contracts have validation errors. Please review the items listed above and fix them, or run this command again with the --force option.
    at NetworkController.<anonymous> (/Users/overlord/DAPPS/unlock/smart-contracts/node_modules/@openzeppelin/cli/src/models/network/NetworkController.ts:135:13)
    at Generator.next (<anonymous>)
    at /Users/overlord/DAPPS/unlock/smart-contracts/node_modules/@openzeppelin/cli/lib/models/network/NetworkController.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/overlord/DAPPS/unlock/smart-contracts/node_modules/@openzeppelin/cli/lib/models/network/NetworkController.js:4:12)
    at NetworkController.push (/Users/overlord/DAPPS/unlock/smart-contracts/node_modules/@openzeppelin/cli/lib/models/network/NetworkController.js:93:16)
    at /Users/overlord/DAPPS/unlock/smart-contracts/node_modules/@openzeppelin/cli/src/scripts/push.ts:21:22
    at Generator.next (<anonymous>)
    at /Users/overlord/DAPPS/unlock/smart-contracts/node_modules/@openzeppelin/cli/lib/scripts/push.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/overlord/DAPPS/unlock/smart-contracts/node_modules/@openzeppelin/cli/lib/scripts/push.js:4:12)
    at push (/Users/overlord/DAPPS/unlock/smart-contracts/node_modules/@openzeppelin/cli/lib/scripts/push.js:18:12)
    at zosDeploy (/Users/overlord/DAPPS/unlock/smart-contracts/migrations/2_deploy_unlock.js:12:9)
    at deployer.then (/Users/overlord/DAPPS/unlock/smart-contracts/migrations/2_deploy_unlock.js:25:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.7 (core: 5.1.7)
Node v10.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

The only difference from master here is in `project.json` under "contracts" I've added:
`"PublicLock": "PublicLock"`

**Comment by nfurfaro** [comment]
closing as this is now scripted, which makes this approach redundent.
