### ISSUE TITLE
Storage issues when trying to upgrade Unlock

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7435]
We recently introduced [very minor changes](https://github.com/unlock-protocol/unlock/pull/7411) to the `Unlock` contract.
As I wanted to prepare the actual upgrade of the deployed contracts, I wanted to try forking the mainnet state locally, test a few things, run the upgrade and test that things were unchanged.

Unfortunately, while doing this, hardhat yields a few issues;

```
 1) Contract: Unlock (on mainnet)
       Unlocck contract
         has locks:
     Error: New storage layout is incompatible

contracts/Unlock.sol:77: Upgraded `globalBaseTokenURI` to an incompatible type
  - Bad upgrade to string

contracts/Unlock.sol:81: Upgraded `globalTokenSymbol` to an incompatible type
  - Bad upgrade to string

contracts/Unlock.sol:88: Upgraded `uniswapOracles` to an incompatible type
  - In mapping(address => contract IUniswapOracle)
    - Bad upgrade from address to contract IUniswapOracle
      at Object.assertStorageUpgradeSafe (node_modules/@openzeppelin/upgrades-core/src/storage/index.ts:54:11)
      at Object.deployImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:37:5)
```

See file in https://github.com/unlock-protocol/unlock/tree/v9-upgrade

**Comment by julien51** [comment]
Similar issues happened in https://github.com/unlock-protocol/unlock/pull/7296 and were fixed successfully in https://github.com/unlock-protocol/unlock/pull/7296/commits/ae8b7ba33d517946676e8cfeb3f9feb4411e6952

**Comment by julien51** [comment]
Fixed in https://github.com/unlock-protocol/unlock/pull/7437
