### ISSUE TITLE
Remove "Eearning" on lock column title

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#795]
**Describe the bug**
Right now, for each lock, we show the balance (the sum of all keys purchased - whatever was previously withdrawn). 
The initial design included the concept of earnings on top of that which is the sum of all keys sold since the beginning. For reason explained in #794 I believe we should remove that feature for now... and hence clarify the column by just showing `Balance`.

<img width="1244" alt="screenshot 2018-12-19 at 22 06 21" src="https://user-images.githubusercontent.com/17735/50261687-a4da4580-03db-11e9-9573-a8f114e03c18.png">

**Comment by vikaskyadav** [comment]
@julien51  I was trying something for this issue and I pulled the new code and it is now showing some weird error. I remember it was working fine 1-2 days ago.

This is the trace:

> Error: Could not find openzeppelin-eth/contracts/ownership/Ownable.sol from any sources; imported from /home/vikasuperman/open-source-projects/unlock/smart-contracts/contracts/Unlock.sol
 at /home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:76:1
    at /home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at next (/home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/~/async/whilst.js:68:1)
    at /home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:64:1
    at /home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/packages/truffle-resolver/fs.js:85:1
    at /home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/~/async/internal/once.js:12:1
    at replenish (/home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/~/async/internal/eachOfLimit.js:61:1)
    at iterateeCallback (/home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/~/async/internal/eachOfLimit.js:50:1)
    at /home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at ReadFileContext.callback (/home/vikasuperman/open-source-projects/unlock/unlock-app/node_modules/truffle/build/webpack:/packages/truffle-resolver/fs.js:81:1)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unlock@1.0.0 deploy-lock: `cd smart-contracts && truffle deploy --reset`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unlock@1.0.0 deploy-lock script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vikasuperman/.npm/_logs/2018-12-20T07_38_04_131Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unlock-app@0.1.0 setup-dev:darwin:freebsd:linux:sunos: `cd .. && (npm run start-ganache -- -b 3 &) && npm run deploy-lock`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unlock-app@0.1.0 setup-dev:darwin:freebsd:linux:sunos script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



I am using Linux Ubuntu 16.04 LTS. Is it because of `run-script-os`?

**Comment by julien51** [comment]
` Could not find openzeppelin-eth/contracts/ownership/Ownable.sol ` makes me think that you might have missing dependencies?
Pull from master again and run `npm run install` from the root of the repo! Thanks!

**Comment by vikaskyadav** [comment]
Hi, I did that., it worked but another issue came in with `pushd`

> sh: 1: pushd: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! unlock-app@0.1.0 set-link:darwin:freebsd:linux:sunos: `pushd src && (test -e artifacts && rm -f artifacts) && ln -s ../../smart-contracts/build artifacts`
npm ERR! spawn ENOENT

**Comment by cellog** [comment]
Ah, I wonder if pushd is a bash extension to sh? Do you have access to a bash shell? If not, try changing the pushd to cd, and see if that works.

**Comment by vikaskyadav** [comment]
haha, it worked! :+1:  :smiley:
