### ISSUE TITLE
rebuild all package deps on yarn build

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8179]
> it looks like when someone builds a library it does not rebuild all of its dependencies.
> For example I just (re)built unlock-js locally but it did not build the contracts package first. I had to go rebuild it manually myself for unlock-js to be using the right values.
> Is there a way to tell yarn to rebuild all of the deps?

We could leverage https://yarn.build for that

**Comment by RishiKumarRay** [comment]
can you give some context to solve this ?

**Comment by julien51** [comment]
@RishiKumarRay ! Thanks for jumping in! We use a monorepo for our code. Right now one of the challenges is that when we build a piece of the code, and it has other pieces as dependencies, we do not necessarily trigger a build in the dependency which might lead to outdated dependencies.

**Comment by clemsos** [comment]
The main idea is that without rebuilding the packages automatically, some part of the repo can become out of sync or go missing, therefore creating unexpected errors. 

The best way to reproduce is to just clone the repo and run a build in one of the folders (e.g. unlock-app). That will fail as the networks or contracts packages  are used but they donc get build automatically. 

Not sure what is the best way to solve this. On one hand, having an automatic rebuild will be useful. On the other hand, adding a complete rebuild of the packages will slow down the repo workflow when developing locally


One approach that @searchableguy pointed at was to use https://yarn.build . I try to be very cautious when adding new tools to the workflow, to avoid lock-ins and possible debt in the future but that is an option worth exploring maybe

**Comment by julien51** [comment]
We could maybe have a Github action for this? 
It checks master out, rebuilds all the packages and opens a PR with changes.
This could run as a cron once a day for example

**Comment by clemsos** [comment]
ok I just tried yarn.build and it does not seem to work.

here is the std of a dry run after issuing ```yarn plugin import https://yarn.build/latest``` (and removing the existing `build` command in the root package.json)


```
An error occured in yarn.build. TypeError: Cannot read property 'stderr' of undefined
    at Dc.checkIfRunIsRequired (/Users/clement/Dev/unlock/unlock-alt/.yarn/plugins/@ojkelly/plugin-all.cjs:118:5482)
    at async Dc.plan (/Users/clement/Dev/unlock/unlock-alt/.yarn/plugins/@ojkelly/plugin-all.cjs:79:968)
    at async Dc.addRunTarget (/Users/clement/Dev/unlock/unlock-alt/.yarn/plugins/@ojkelly/plugin-all.cjs:118:3529)
    at async qc (/Users/clement/Dev/unlock/unlock-alt/.yarn/plugins/@ojkelly/plugin-all.cjs:127:639)
    at async /Users/clement/Dev/unlock/unlock-alt/.yarn/plugins/@ojkelly/plugin-all.cjs:163:4638
    at async Function.start (/Users/clement/Dev/unlock/unlock-alt/.yarn/releases/yarn-3.1.0-rc.7.cjs:276:2287)
    at async Zt.execute (/Users/clement/Dev/unlock/unlock-alt/.yarn/plugins/@ojkelly/plugin-all.cjs:163:3760)
    at async Zt.validateAndExecute (/Users/clement/Dev/unlock/unlock-alt/.yarn/releases/yarn-3.1.0-rc.7.cjs:198:620)
    at async os.run (/Users/clement/Dev/unlock/unlock-alt/.yarn/releases/yarn-3.1.0-rc.7.cjs:212:1846)
    at async os.runExit (/Users/clement/Dev/unlock/unlock-alt/.yarn/releases/yarn-3.1.0-rc.7.cjs:212:2013)

[ build for All ]---------------------------------------------------------------

--[ Output: packages/types ]----------------------------------------------------
error TS5055: Cannot write file '/Users/clement/Dev/unlock/unlock-alt/packages/types/dist/dist/index.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/clement/Dev/unlock/unlock-alt/packages/types/dist/dist/index.js' because it would overwrite input file.
error TS5055: Cannot write file '/Users/clement/Dev/unlock/unlock-alt/packages/types/dist/dist/types/unlockTypes.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/clement/Dev/unlock/unlock-alt/packages/types/dist/dist/types/unlockTypes.js' because it would overwrite input file.
error TS5055: Cannot write file '/Users/clement/Dev/unlock/unlock-alt/packages/types/dist/src/index.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/clement/Dev/unlock/unlock-alt/packages/types/dist/src/index.js' because it would overwrite input file.
error TS5055: Cannot write file '/Users/clement/Dev/unlock/unlock-alt/packages/types/dist/src/types/unlockTypes.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/clement/Dev/unlock/unlock-alt/packages/types/dist/src/types/unlockTypes.js' because it would overwrite input file.
--------------------------------------------------------------------------------
ERROR for script build for All
The following packages returned an error.
- packages/types
- packages/ui

[ Summary ]---------------------------------------------------------------------
Success: 0
Up to date: 0
Fail: 2
Skipped: 6
Excluded: 0
Total: 8
---
Cumulative: (cpu): 1m 2.05s
Saved: 30.96s
Runtime (wall): 31.09s
[ build finished with 2 errors ]----------------------------------[ yarn.build ]


➤ YN0009: Build failed
➤ YN0000: Failed with errors in 31s 261ms
```

**Comment by clemsos** [comment]
I just run across this tool and looks worth investigating to speed up builds and deps 

https://turbo.build/repo/docs/handbook/workspaces
