### ISSUE TITLE
ABI build command is failing for unlockjs

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#8617]
**Describe the bug**

**To Reproduce**
1. Go to unlockjs folder
2. Run `yarn install`
3. Run `yarn build:abis`

```
home/searchableguy/Work/unlock/packages/unlock-js/scripts/compressAbi.js:64
  const signatures = abi.abi
                         ^

TypeError: Cannot read properties of undefined (reading 'abi')
    at parseABI (/home/searchableguy/Work/unlock/packages/unlock-js/scripts/compressAbi.js:64:26)
    at /home/searchableguy/Work/unlock/packages/unlock-js/scripts/compressAbi.js:23:12
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/home/searchableguy/Work/unlock/packages/unlock-js/scripts/compressAbi.js:20:34)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by julien51** [comment]
Maybe @clemsos knows a bit more?

**Comment by clemsos** [comment]
You may be missing the last version of the contracts package. Maybe you need to run 'yarn build' at root level of the mono repo to rebuild the package?

**Comment by searchableguy** [comment]
That was the case. Re-running the yarn build-in contract directory fixed it.
