### ISSUE TITLE
ERC20 contract allowance for gas refund

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8679]
**Describe the bug**

Currently the `_gasRefund` function use the ERC20 `transferFrom` method to send tokens back to the sender. 

https://github.com/unlock-protocol/unlock/blob/3d27e503eff6df518cc50dfe4ad879dd8e0090cb/smart-contracts/contracts/mixins/MixinPurchase.sol#L278

In most ERC20 contracts, this will decrease allowance (see OZ example)

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/token/ERC20/ERC20.sol#L164

This cause the gas refund to reverts when used with most ERC20, has no allowance is set (the contract should send the funds directly).

The error was not apparent in the tests, as the hardly-difficult lib ERC20 does not have such feature.

**To Reproduce**

1. Check the [`gas-refund-bug`](https://github.com/unlock-protocol/unlock/blob/8e3b93f0c3b0c1ff0d8d883e2dbe8b01ca029e06/smart-contracts/scripts/renew.js) branch
2. start a hardhat node
3. `yarn hardhat deploy --network localhost`
4. update the unlock address in [`scripts/renew.js`](https://github.com/unlock-protocol/unlock/blob/8e3b93f0c3b0c1ff0d8d883e2dbe8b01ca029e06/smart-contracts/scripts/renew.js)
5. `yarn hardhat run scripts/renew.js --network localhost`

In `renew.js`, if you set the variable `useHardlyDifficult` to `false`, the script fails w the following error

```
LOCK DEPLOY > deployed to : 0x638f0f65Ba5e4d70401e9deea7aA0e8BeE68b6F8 (tx: 0xd876ac877f4d9514e7f98151b65626a2de5f1f297d49f4ac942de605793d4114)
my lock
BigNumber { value: "1000000000000" }
BigNumber { value: "1000000000000" }
BigNumber { value: "0" }
BigNumber { value: "150000" }
ProviderError: Error: VM Exception while processing transaction: reverted with reason string 'ERC20: transfer amount exceeds allowance'
    at HttpProvider.request (/Users/clement/Dev/unlock/unlock/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at HDWalletProvider.request (/Users/clement/Dev/unlock/unlock/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EthersProviderWrapper.send (/Users/clement/Dev/unlock/unlock/smart-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

When setting `useHardlyDifficult ` to `true`, it will succeed with 

```
LOCK DEPLOY > deployed to : 0x9f9D6AF359b4540C7b50ec0D7d6D52c8A3f5f2FA (tx: 0x314c9eed3ce4f1341a71b507a02024af9ecb8bd36b74519bc4e51abfefa73d4d)
my lock
BigNumber { value: "1000000000000" }
BigNumber { value: "1000000000000" }
BigNumber { value: "0" }
BigNumber { value: "150000" }
waiting for key (1) to expire...
[
  BigNumber { value: "1" },
  BigNumber { value: "1651158887" },
  tokenId: BigNumber { value: "1" },
  newTimestamp: BigNumber { value: "1651158887" }
]
```

**Expected behavior**

The ERC20 amount of gas refund should be sent directly to the `msg.sender`, likely using `erc20.transfer(msg.sender)` instead of `transferFrom(address(this), msg.sender)`

**Comment by clemsos** [comment]
Currently we can use `lock.approveBeneficiary(lock.address, keyPrice + gasRefund)` as a workaround...
